---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  handlers:
    - import_tasks: handlers/ca-cert.yml
      when: install_custom_certs

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

    # - pause:
    #    prompt: "Enter your new passphrase for generating SSH keys:"
    #   when: generate_ssh_keys
    #   register: ssh_passphrase


  roles:
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']

  tasks:
    ## SYSTEM TASKS

    - include_tasks: tasks/rh_subscription_simple.yml
      when: rhss_subscribe

    - include_tasks: tasks/software.yml
      when: install_software

    - include_tasks: tasks/users.yml
      when: configure_users

    - include_tasks: tasks/sudoers.yml
      when: configure_sudoers

    - include_tasks: tasks/ansible-setup.yml
      when: configure_ansible

    - include_tasks: tasks/openstack_client.yml
      when: install_openstack_client

    ## USER TASKS
    - include_tasks: tasks/ssh.yml
      when: configure_ssh_client or generate_ssh_keys

    - include_tasks: tasks/clone_repos.yml
      when: clone_repos

    # - include_tasks: tasks/terminal.yml
    #   when: configure_terminal

    # - include_tasks: tasks/osx.yml
    #   when: configure_osx
    #   tags: ['osx']

    # - include_tasks: tasks/extra-packages.yml
    #   tags: ['extra-packages']

    - name: create .emacs.d directory
      file:
        path: ~/.emacs.d
        state: directory
      when: configure_dotfiles

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
